### ISSUE TITLE
Docs: [Advanced] Experiment Config.yaml Files changed slightly

### ISSUE THREAD

**Issue by parkerrobbins** [pushkin-consortium/pushkin#55]
[Experiment Config.yaml Files](https://languagelearninglab.gitbook.io/pushkin/advanced/experiment-structure/experiment-config-files).

Here is my `config.yaml` for an experiment called `lex`. Line 28, `text` is missing from the preview and from the explanations [here](https://languagelearninglab.gitbook.io/pushkin/advanced/experiment-structure/experiment-config-files#logo-tagline-duration-other).  

```
experimentName: lex
shortName: lex
apiControllers:
  mountPath: lex
  location: api controllers
  name: mycontroller
worker:
  location: worker
  service:
    image: lex
    links:
      - message-queue
      - test_db
    environment:
      - 'AMQP_ADDRESS=amqp://message-queue:5672'
      - DB_USER=postgres
      - DB_PASS=
      - DB_URL=test_db
      - DB_NAME=test_db
webPage:
  location: web page
migrations:
  location: migrations
seeds:
  location: ''
database: localtestdb
logo: logo512.png
text: Enter your experiment description here.
tagline: Be a citizen scientist! Try this quiz.
duration: ''
```
